theme: jekyll-theme-architect
author: Alicja Bednarzewska
title: BAIN Lerntagebuch
description: Das ist ein Lerntagebuch zum Modul BAIN. Beschrieben werden jeweils die einzelnen Einheiten und ein Einführgs-/Abschlussartikel. 
email: alicja.bednarzewska@stud.fhgr.ch
